#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : fast_float
Version  : 8.0.2
Release  : 1
URL      : https://github.com/fastfloat/fast_float/archive/refs/tags/v8.0.2.tar.gz
Source0  : https://github.com/fastfloat/fast_float/archive/refs/tags/v8.0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSL-1.0 MIT
Requires: fast_float-data = %{version}-%{release}
Requires: fast_float-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
## fast_float number parsing library: 4x faster than strtod
[![Ubuntu 22.04 CI (GCC 11)](https://github.com/fastfloat/fast_float/actions/workflows/ubuntu22.yml/badge.svg)](https://github.com/fastfloat/fast_float/actions/workflows/ubuntu22.yml)

%package data
Summary: data components for the fast_float package.
Group: Data

%description data
data components for the fast_float package.


%package dev
Summary: dev components for the fast_float package.
Group: Development
Requires: fast_float-data = %{version}-%{release}
Provides: fast_float-devel = %{version}-%{release}
Requires: fast_float = %{version}-%{release}

%description dev
dev components for the fast_float package.


%package license
Summary: license components for the fast_float package.
Group: Default

%description license
license components for the fast_float package.


%prep
%setup -q -n fast_float-8.0.2
cd %{_builddir}/fast_float-8.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742589434
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1742589434
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fast_float
cp %{_builddir}/fast_float-%{version}/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/fast_float/17d9f7912c62b7feadce3c1054e64ab70ade5111 || :
cp %{_builddir}/fast_float-%{version}/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/fast_float/3f317fbb3e08fd99169d2e77105d562ea0e482c7 || :
cp %{_builddir}/fast_float-%{version}/LICENSE-MIT %{buildroot}/usr/share/package-licenses/fast_float/11e6be99fa6ad788d013a38598c7da3e5d90efbe || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/fast_float/ascii_number.h
/usr/include/fast_float/bigint.h
/usr/include/fast_float/constexpr_feature_detect.h
/usr/include/fast_float/decimal_to_binary.h
/usr/include/fast_float/digit_comparison.h
/usr/include/fast_float/fast_float.h
/usr/include/fast_float/fast_table.h
/usr/include/fast_float/float_common.h
/usr/include/fast_float/parse_number.h

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fast_float/11e6be99fa6ad788d013a38598c7da3e5d90efbe
/usr/share/package-licenses/fast_float/17d9f7912c62b7feadce3c1054e64ab70ade5111
/usr/share/package-licenses/fast_float/3f317fbb3e08fd99169d2e77105d562ea0e482c7
